### ISSUE TITLE
Add support Ubuntu 20.04 / 20.10 and RHEL 8

### ISSUE THREAD

**Issue by alexkorotysh** [aitalian/puppet-mspackages#2]
Hi
Could you please update the repository setting in the module with the current supported OS

https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#ubuntu17

https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#redhat17

**Comment by aitalian** [comment]
Thank you @alexkorotysh I've made the requisite changes and released version 1.0.0.
